// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Js_mapperRt = require("bs-platform/lib/js/js_mapperRt.js");

var jsMapperConstantArray = /* array */[
  /* tuple */[
    836965712,
    "Kiwi"
  ],
  /* tuple */[
    873223388,
    "Watermelon"
  ],
  /* tuple */[
    929625402,
    "Apple"
  ]
];

function fruitToJs(param) {
  return Js_mapperRt.binSearch(3, param, jsMapperConstantArray);
}

function fruitFromJs(param) {
  return Js_mapperRt.revSearch(3, jsMapperConstantArray, param);
}

var appleString = fruitToJs(/* Apple */929625402);

var kiwiString = fruitToJs(/* Kiwi */836965712);

console.log(appleString);

exports.fruitToJs   = fruitToJs;
exports.fruitFromJs = fruitFromJs;
exports.appleString = appleString;
exports.kiwiString  = kiwiString;
/* appleString Not a pure module */
