// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Curry    = require("bs-platform/lib/js/curry.js");
var Readline = require("readline");

var $$process = ( process );

var rl = Readline.createInterface({
      input: $$process.stdin,
      output: $$process.stdout
    });

Curry._2(rl[/* question */0], "Test", (function (answer) {
        if (answer) {
          console.log("ok this text" + answer[0]);
          return /* () */0;
        } else {
          console.log("You must write value");
          return /* () */0;
        }
      }));

exports.$$process = $$process;
exports.rl        = rl;
/* process Not a pure module */
