// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Readline = require("readline");

var $$process = ( process );

var Readline$1 = /* module */[];

var Node = /* module */[
  /* process */$$process,
  /* Readline */Readline$1
];

var rl = Readline.createInterface({
      input: $$process.stdin,
      output: $$process.stdout
    });

rl.question("Test : ", (function (answer) {
        if (answer) {
          console.log("ok this text ==> " + answer[0]);
          return /* () */0;
        } else {
          console.log("You must write value");
          return /* () */0;
        }
      }));

exports.Node = Node;
exports.rl   = rl;
/* process Not a pure module */
