// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Fs   = require("fs");
var Path = require("path");

function getNorm(e) {
  switch (e) {
    case 0 : 
        return "hex";
    case 1 : 
        return "utf8";
    case 2 : 
        return "ascii";
    case 3 : 
        return "latin1";
    case 4 : 
        return "base64";
    
  }
}

var Encoding = /* module */[/* getNorm */getNorm];

var dirname = typeof (__dirname) === "undefined" ? undefined : (__dirname);

function readFile(path, norm, callback) {
  return Fs.readFile(path, getNorm(norm), callback);
}

if (dirname !== undefined) {
  readFile(Path.resolve(dirname, "test.txt"), /* UTF8 */1, (function (err, _) {
          var match = +err;
          if (match !== 0) {
            console.log("Error");
            return /* () */0;
          } else {
            console.log("Ok");
            return /* () */0;
          }
        }));
} else {
  console.log("no __dirname");
}

var dirname$1 = dirname === undefined ? /* None */0 : [dirname];

exports.Encoding = Encoding;
exports.dirname  = dirname$1;
exports.readFile = readFile;
/* dirname Not a pure module */
